name: Print File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  read_the_file:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: Read the file
        runs: |
          ls -l
          cat hello_world.txt